baseURL: "https://frankdoka.com"
languageCode: en-us
title: Frank Doka
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: Stats
      name: Stats
      url: /stats
      weight: 50
    - identifier: Login
      name: Login
      url: "https://login.frankdoka.com"
      weight: 50
    - identifier: search
      name: Search
      url: /search
      weight: 60

params:
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  env: production

  profileMode:
    enabled: true
    title: "Frank Doka"
    subtitle: "<br>Greetings!<br><br>Welcome to my digital corner where I explore the vast world of technology. I share insights and lessons that have shaped my journey.<br><br>My interests include cloud engineering, DevOps and software development.<p><br>Dive in to discover more about me and my tech adventures.<br><br>"  
    imageUrl: "home/Untitled.png"
    imageWidth: 300
    imageHeight: 290
    buttons:
        - name: About Me
          url: /about
     #   url: ""
     
  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/frank-doka-64951828b/"
   # - name: "cv"
     # url: ""

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true

deployment:
  targets:
    - name: frankdoka.com
      URL: 's3://frankdoka.com?region=us-east-1'
      cloudFrontDistributionID: 'E3277YOQ3YWDYR'
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: 'max-age=630720000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
